/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include <app-common/zap-generated/cluster-objects.h>
#include <app/data-model/WrappedStructEncoder.h>

namespace chip {
namespace app {

bool CommandNeedsTimedInvoke(ClusterId aCluster, CommandId aCommand)
{
    // Maybe it would be smaller code to codegen a table and walk over it?
    // Not sure.
    switch (aCluster)
    {
    case Clusters::AdministratorCommissioning::Id: {
        switch (aCommand)
        {
        case Clusters::AdministratorCommissioning::Commands::OpenCommissioningWindow::Id:
        case Clusters::AdministratorCommissioning::Commands::OpenBasicCommissioningWindow::Id:
        case Clusters::AdministratorCommissioning::Commands::RevokeCommissioning::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::EnergyEvse::Id: {
        switch (aCommand)
        {
        case Clusters::EnergyEvse::Commands::Disable::Id:
        case Clusters::EnergyEvse::Commands::EnableCharging::Id:
        case Clusters::EnergyEvse::Commands::EnableDischarging::Id:
        case Clusters::EnergyEvse::Commands::StartDiagnostics::Id:
        case Clusters::EnergyEvse::Commands::SetTargets::Id:
        case Clusters::EnergyEvse::Commands::GetTargets::Id:
        case Clusters::EnergyEvse::Commands::ClearTargets::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::DoorLock::Id: {
        switch (aCommand)
        {
        case Clusters::DoorLock::Commands::LockDoor::Id:
        case Clusters::DoorLock::Commands::UnlockDoor::Id:
        case Clusters::DoorLock::Commands::UnlockWithTimeout::Id:
        case Clusters::DoorLock::Commands::SetUser::Id:
        case Clusters::DoorLock::Commands::ClearUser::Id:
        case Clusters::DoorLock::Commands::SetCredential::Id:
        case Clusters::DoorLock::Commands::ClearCredential::Id:
        case Clusters::DoorLock::Commands::UnboltDoor::Id:
        case Clusters::DoorLock::Commands::SetAliroReaderConfig::Id:
        case Clusters::DoorLock::Commands::ClearAliroReaderConfig::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::ThreadNetworkDirectory::Id: {
        switch (aCommand)
        {
        case Clusters::ThreadNetworkDirectory::Commands::AddNetwork::Id:
        case Clusters::ThreadNetworkDirectory::Commands::RemoveNetwork::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::AccountLogin::Id: {
        switch (aCommand)
        {
        case Clusters::AccountLogin::Commands::GetSetupPIN::Id:
        case Clusters::AccountLogin::Commands::Login::Id:
        case Clusters::AccountLogin::Commands::Logout::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::UnitTesting::Id: {
        switch (aCommand)
        {
        case Clusters::UnitTesting::Commands::TimedInvokeRequest::Id:
            return true;
        default:
            return false;
        }
    }
    default:
        break;
    }

    return false;
}

bool CommandIsFabricScoped(ClusterId aCluster, CommandId aCommand)
{
    // Maybe it would be smaller code to codegen a table and walk over it?
    // Not sure.
    switch (aCluster)
    {
    case Clusters::Identify::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::Groups::Id: {
        switch (aCommand)
        {
        case Clusters::Groups::Commands::AddGroup::Id:
            return true;
        case Clusters::Groups::Commands::ViewGroup::Id:
            return true;
        case Clusters::Groups::Commands::GetGroupMembership::Id:
            return true;
        case Clusters::Groups::Commands::RemoveGroup::Id:
            return true;
        case Clusters::Groups::Commands::RemoveAllGroups::Id:
            return true;
        case Clusters::Groups::Commands::AddGroupIfIdentifying::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::OnOff::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::LevelControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::AccessControl::Id: {
        switch (aCommand)
        {
        case Clusters::AccessControl::Commands::ReviewFabricRestrictions::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::Actions::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::BasicInformation::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OtaSoftwareUpdateProvider::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OtaSoftwareUpdateRequestor::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::GeneralCommissioning::Id: {
        switch (aCommand)
        {
        case Clusters::GeneralCommissioning::Commands::CommissioningComplete::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::NetworkCommissioning::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DiagnosticLogs::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::GeneralDiagnostics::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::SoftwareDiagnostics::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ThreadNetworkDiagnostics::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WiFiNetworkDiagnostics::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::EthernetNetworkDiagnostics::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::TimeSynchronization::Id: {
        switch (aCommand)
        {
        case Clusters::TimeSynchronization::Commands::SetTrustedTimeSource::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::BridgedDeviceBasicInformation::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::AdministratorCommissioning::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OperationalCredentials::Id: {
        switch (aCommand)
        {
        case Clusters::OperationalCredentials::Commands::UpdateNOC::Id:
            return true;
        case Clusters::OperationalCredentials::Commands::UpdateFabricLabel::Id:
            return true;
        case Clusters::OperationalCredentials::Commands::SetVIDVerificationStatement::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::GroupKeyManagement::Id: {
        switch (aCommand)
        {
        case Clusters::GroupKeyManagement::Commands::KeySetWrite::Id:
            return true;
        case Clusters::GroupKeyManagement::Commands::KeySetRead::Id:
            return true;
        case Clusters::GroupKeyManagement::Commands::KeySetRemove::Id:
            return true;
        case Clusters::GroupKeyManagement::Commands::KeySetReadAllIndices::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::IcdManagement::Id: {
        switch (aCommand)
        {
        case Clusters::IcdManagement::Commands::RegisterClient::Id:
            return true;
        case Clusters::IcdManagement::Commands::UnregisterClient::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::Timer::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OvenCavityOperationalState::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OvenMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ModeSelect::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::LaundryWasherMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::RefrigeratorAndTemperatureControlledCabinetMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::RvcRunMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::RvcCleanMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::TemperatureControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DishwasherMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::SmokeCoAlarm::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DishwasherAlarm::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::MicrowaveOvenControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::OperationalState::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::RvcOperationalState::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ScenesManagement::Id: {
        switch (aCommand)
        {
        case Clusters::ScenesManagement::Commands::AddScene::Id:
            return true;
        case Clusters::ScenesManagement::Commands::ViewScene::Id:
            return true;
        case Clusters::ScenesManagement::Commands::RemoveScene::Id:
            return true;
        case Clusters::ScenesManagement::Commands::RemoveAllScenes::Id:
            return true;
        case Clusters::ScenesManagement::Commands::StoreScene::Id:
            return true;
        case Clusters::ScenesManagement::Commands::RecallScene::Id:
            return true;
        case Clusters::ScenesManagement::Commands::GetSceneMembership::Id:
            return true;
        case Clusters::ScenesManagement::Commands::CopyScene::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::HepaFilterMonitoring::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ActivatedCarbonFilterMonitoring::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::BooleanStateConfiguration::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ValveConfigurationAndControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WaterHeaterManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::CommodityPrice::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DemandResponseLoadControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::Messages::Id: {
        switch (aCommand)
        {
        case Clusters::Messages::Commands::PresentMessagesRequest::Id:
            return true;
        case Clusters::Messages::Commands::CancelMessagesRequest::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::DeviceEnergyManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::EnergyEvse::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::EnergyEvseMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WaterHeaterMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DeviceEnergyManagementMode::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::DoorLock::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WindowCovering::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ClosureControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ClosureDimension::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ServiceArea::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::Thermostat::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::FanControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ColorControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WiFiNetworkManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ThreadBorderRouterManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ThreadNetworkDirectory::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::Channel::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::TargetNavigator::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::MediaPlayback::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::MediaInput::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::LowPower::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::KeypadInput::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ContentLauncher::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::AudioOutput::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ApplicationLauncher::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::AccountLogin::Id: {
        switch (aCommand)
        {
        case Clusters::AccountLogin::Commands::GetSetupPIN::Id:
            return true;
        case Clusters::AccountLogin::Commands::Login::Id:
            return true;
        case Clusters::AccountLogin::Commands::Logout::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::ContentControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ContentAppObserver::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::ZoneManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::CameraAvStreamManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::CameraAvSettingsUserLevelManagement::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::WebRTCTransportProvider::Id: {
        switch (aCommand)
        {
        case Clusters::WebRTCTransportProvider::Commands::SolicitOffer::Id:
            return true;
        case Clusters::WebRTCTransportProvider::Commands::ProvideOffer::Id:
            return true;
        case Clusters::WebRTCTransportProvider::Commands::ProvideAnswer::Id:
            return true;
        case Clusters::WebRTCTransportProvider::Commands::ProvideICECandidates::Id:
            return true;
        case Clusters::WebRTCTransportProvider::Commands::EndSession::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::WebRTCTransportRequestor::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::PushAvStreamTransport::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::Chime::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::CommodityTariff::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::CommissionerControl::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::TlsCertificateManagement::Id: {
        switch (aCommand)
        {
        case Clusters::TlsCertificateManagement::Commands::ProvisionRootCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::FindRootCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::LookupRootCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::RemoveRootCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::TLSClientCSR::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::FindClientCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::LookupClientCertificate::Id:
            return true;
        case Clusters::TlsCertificateManagement::Commands::RemoveClientCertificate::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::TlsClientManagement::Id: {
        switch (aCommand)
        {
        case Clusters::TlsClientManagement::Commands::ProvisionEndpoint::Id:
            return true;
        case Clusters::TlsClientManagement::Commands::FindEndpoint::Id:
            return true;
        case Clusters::TlsClientManagement::Commands::RemoveEndpoint::Id:
            return true;
        default:
            return false;
        }
    }
    case Clusters::UnitTesting::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::FaultInjection::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    case Clusters::SampleMei::Id: {
        switch (aCommand)
        {
        default:
            return false;
        }
    }
    }
    return false;
}

bool CommandHasLargePayload(ClusterId aCluster, CommandId aCommand)
{
    if ((aCluster == Clusters::CameraAvStreamManagement::Id) &&
        (aCommand == Clusters::CameraAvStreamManagement::Commands::CaptureSnapshot::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::CameraAvStreamManagement::Id) &&
        (aCommand == Clusters::CameraAvStreamManagement::Commands::CaptureSnapshotResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::SolicitOffer::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::SolicitOfferResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::ProvideOffer::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::ProvideOfferResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::ProvideAnswer::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::ProvideICECandidates::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportProvider::Id) &&
        (aCommand == Clusters::WebRTCTransportProvider::Commands::EndSession::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportRequestor::Id) &&
        (aCommand == Clusters::WebRTCTransportRequestor::Commands::Offer::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportRequestor::Id) &&
        (aCommand == Clusters::WebRTCTransportRequestor::Commands::Answer::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportRequestor::Id) &&
        (aCommand == Clusters::WebRTCTransportRequestor::Commands::ICECandidates::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::WebRTCTransportRequestor::Id) && (aCommand == Clusters::WebRTCTransportRequestor::Commands::End::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::PushAvStreamTransport::Id) &&
        (aCommand == Clusters::PushAvStreamTransport::Commands::AllocatePushTransport::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::PushAvStreamTransport::Id) &&
        (aCommand == Clusters::PushAvStreamTransport::Commands::AllocatePushTransportResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::PushAvStreamTransport::Id) &&
        (aCommand == Clusters::PushAvStreamTransport::Commands::FindTransport::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::PushAvStreamTransport::Id) &&
        (aCommand == Clusters::PushAvStreamTransport::Commands::FindTransportResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::ProvisionRootCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::ProvisionRootCertificateResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::FindRootCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::FindRootCertificateResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::LookupRootCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::LookupRootCertificateResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::RemoveRootCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::TLSClientCSR::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::TLSClientCSRResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::ProvisionClientCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::FindClientCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::FindClientCertificateResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::LookupClientCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::LookupClientCertificateResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsCertificateManagement::Id) &&
        (aCommand == Clusters::TlsCertificateManagement::Commands::RemoveClientCertificate::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsClientManagement::Id) &&
        (aCommand == Clusters::TlsClientManagement::Commands::ProvisionEndpoint::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsClientManagement::Id) &&
        (aCommand == Clusters::TlsClientManagement::Commands::ProvisionEndpointResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsClientManagement::Id) && (aCommand == Clusters::TlsClientManagement::Commands::FindEndpoint::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsClientManagement::Id) &&
        (aCommand == Clusters::TlsClientManagement::Commands::FindEndpointResponse::Id))
    {
        return true;
    }
    if ((aCluster == Clusters::TlsClientManagement::Id) &&
        (aCommand == Clusters::TlsClientManagement::Commands::RemoveEndpoint::Id))
    {
        return true;
    }
    return false;
}

} // namespace app
} // namespace chip
