name: Stop CI actions
description: Trigger a stop CI worflows for this commit
inputs:
  github_token:
    description: "Github token to use"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup pip modules we use
      shell: bash
      run: |
          pip install     \
              click       \
              coloredlogs \
              pygithub    \
              && echo "DONE installint python prerequisites"
    - name: Cancel GH worflows
      shell: bash
      run: |
        # We assume a checkout is available
        scripts/tools/cancel_workflows_for_pr.py                        \
            --pull-request  "${{ github.event.number }}"                \
            --commit-sha    "${{ github.event.pull_request.head.sha }}" \
            --skip-workflow "${{ github.workflow }}"                    \
            --gh-api-token  "${{ inputs.github_token }}"
