/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>
#include <clusters/ClosureControl/Structs.h>

namespace chip {
namespace app {
namespace Clusters {
namespace ClosureControl {
namespace Structs {

namespace OverallStateStruct {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kPositioning), positioning);
    encoder.Encode(to_underlying(Fields::kLatching), latching);
    encoder.Encode(to_underlying(Fields::kSpeed), speed);
    encoder.Encode(to_underlying(Fields::kExtraInfo), extraInfo);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        auto __element = __iterator.Next();
        if (std::holds_alternative<CHIP_ERROR>(__element))
        {
            return std::get<CHIP_ERROR>(__element);
        }

        CHIP_ERROR err              = CHIP_NO_ERROR;
        const uint8_t __context_tag = std::get<uint8_t>(__element);

        if (__context_tag == to_underlying(Fields::kPositioning))
        {
            err = DataModel::Decode(reader, positioning);
        }
        else if (__context_tag == to_underlying(Fields::kLatching))
        {
            err = DataModel::Decode(reader, latching);
        }
        else if (__context_tag == to_underlying(Fields::kSpeed))
        {
            err = DataModel::Decode(reader, speed);
        }
        else if (__context_tag == to_underlying(Fields::kExtraInfo))
        {
            err = DataModel::Decode(reader, extraInfo);
        }
        else
        {
        }

        ReturnErrorOnFailure(err);
    }
}

} // namespace OverallStateStruct

namespace OverallTargetStruct {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kPosition), position);
    encoder.Encode(to_underlying(Fields::kLatch), latch);
    encoder.Encode(to_underlying(Fields::kSpeed), speed);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        auto __element = __iterator.Next();
        if (std::holds_alternative<CHIP_ERROR>(__element))
        {
            return std::get<CHIP_ERROR>(__element);
        }

        CHIP_ERROR err              = CHIP_NO_ERROR;
        const uint8_t __context_tag = std::get<uint8_t>(__element);

        if (__context_tag == to_underlying(Fields::kPosition))
        {
            err = DataModel::Decode(reader, position);
        }
        else if (__context_tag == to_underlying(Fields::kLatch))
        {
            err = DataModel::Decode(reader, latch);
        }
        else if (__context_tag == to_underlying(Fields::kSpeed))
        {
            err = DataModel::Decode(reader, speed);
        }
        else
        {
        }

        ReturnErrorOnFailure(err);
    }
}

} // namespace OverallTargetStruct
} // namespace Structs
} // namespace ClosureControl
} // namespace Clusters
} // namespace app
} // namespace chip
