/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

void MatterIdentifyPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterScenesPluginServerInitCallback();
void MatterOnOffPluginServerInitCallback();
void MatterOnOffSwitchConfigurationPluginServerInitCallback();
void MatterLevelControlPluginServerInitCallback();
void MatterBinaryInputBasicPluginServerInitCallback();
void MatterPulseWidthModulationPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterBindingPluginServerInitCallback();
void MatterAccessControlPluginServerInitCallback();
void MatterActionsPluginServerInitCallback();
void MatterBasicPluginServerInitCallback();
void MatterOtaSoftwareUpdateProviderPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterLocalizationConfigurationPluginServerInitCallback();
void MatterTimeFormatLocalizationPluginServerInitCallback();
void MatterUnitLocalizationPluginServerInitCallback();
void MatterPowerSourceConfigurationPluginServerInitCallback();
void MatterPowerSourcePluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterDiagnosticLogsPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterEthernetNetworkDiagnosticsPluginServerInitCallback();
void MatterTimeSynchronizationPluginServerInitCallback();
void MatterBridgedDeviceBasicPluginServerInitCallback();
void MatterSwitchPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterFixedLabelPluginServerInitCallback();
void MatterUserLabelPluginServerInitCallback();
void MatterProxyConfigurationPluginServerInitCallback();
void MatterProxyDiscoveryPluginServerInitCallback();
void MatterProxyValidPluginServerInitCallback();
void MatterBooleanStatePluginServerInitCallback();
void MatterModeSelectPluginServerInitCallback();
void MatterDoorLockPluginServerInitCallback();
void MatterWindowCoveringPluginServerInitCallback();
void MatterBarrierControlPluginServerInitCallback();
void MatterPumpConfigurationAndControlPluginServerInitCallback();
void MatterThermostatPluginServerInitCallback();
void MatterFanControlPluginServerInitCallback();
void MatterThermostatUserInterfaceConfigurationPluginServerInitCallback();
void MatterColorControlPluginServerInitCallback();
void MatterBallastConfigurationPluginServerInitCallback();
void MatterIlluminanceMeasurementPluginServerInitCallback();
void MatterTemperatureMeasurementPluginServerInitCallback();
void MatterPressureMeasurementPluginServerInitCallback();
void MatterFlowMeasurementPluginServerInitCallback();
void MatterRelativeHumidityMeasurementPluginServerInitCallback();
void MatterOccupancySensingPluginServerInitCallback();
void MatterWakeOnLanPluginServerInitCallback();
void MatterChannelPluginServerInitCallback();
void MatterTargetNavigatorPluginServerInitCallback();
void MatterMediaPlaybackPluginServerInitCallback();
void MatterMediaInputPluginServerInitCallback();
void MatterLowPowerPluginServerInitCallback();
void MatterKeypadInputPluginServerInitCallback();
void MatterContentLauncherPluginServerInitCallback();
void MatterAudioOutputPluginServerInitCallback();
void MatterApplicationLauncherPluginServerInitCallback();
void MatterApplicationBasicPluginServerInitCallback();
void MatterAccountLoginPluginServerInitCallback();
void MatterElectricalMeasurementPluginServerInitCallback();
void MatterTestClusterPluginServerInitCallback();
void MatterFaultInjectionPluginServerInitCallback();
