/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include <app/data-model/StructDecodeIterator.h>
#include <app/data-model/WrappedStructEncoder.h>
#include <clusters/MicrowaveOvenControl/Commands.h>

namespace chip {
namespace app {
namespace Clusters {
namespace MicrowaveOvenControl {
namespace Commands {
namespace SetCookingParameters {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kCookMode), cookMode);
    encoder.Encode(to_underlying(Fields::kCookTime), cookTime);
    encoder.Encode(to_underlying(Fields::kPowerSetting), powerSetting);
    encoder.Encode(to_underlying(Fields::kWattSettingIndex), wattSettingIndex);
    encoder.Encode(to_underlying(Fields::kStartAfterSetting), startAfterSetting);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        auto __element = __iterator.Next();
        if (std::holds_alternative<CHIP_ERROR>(__element))
        {
            return std::get<CHIP_ERROR>(__element);
        }

        CHIP_ERROR err              = CHIP_NO_ERROR;
        const uint8_t __context_tag = std::get<uint8_t>(__element);

        if (__context_tag == to_underlying(Fields::kCookMode))
        {
            err = DataModel::Decode(reader, cookMode);
        }
        else if (__context_tag == to_underlying(Fields::kCookTime))
        {
            err = DataModel::Decode(reader, cookTime);
        }
        else if (__context_tag == to_underlying(Fields::kPowerSetting))
        {
            err = DataModel::Decode(reader, powerSetting);
        }
        else if (__context_tag == to_underlying(Fields::kWattSettingIndex))
        {
            err = DataModel::Decode(reader, wattSettingIndex);
        }
        else if (__context_tag == to_underlying(Fields::kStartAfterSetting))
        {
            err = DataModel::Decode(reader, startAfterSetting);
        }
        else
        {
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace SetCookingParameters.
namespace AddMoreTime {
CHIP_ERROR Type::Encode(TLV::TLVWriter & aWriter, TLV::Tag aTag) const
{
    DataModel::WrappedStructEncoder encoder{ aWriter, aTag };
    encoder.Encode(to_underlying(Fields::kTimeToAdd), timeToAdd);
    return encoder.Finalize();
}

CHIP_ERROR DecodableType::Decode(TLV::TLVReader & reader)
{
    detail::StructDecodeIterator __iterator(reader);
    while (true)
    {
        auto __element = __iterator.Next();
        if (std::holds_alternative<CHIP_ERROR>(__element))
        {
            return std::get<CHIP_ERROR>(__element);
        }

        CHIP_ERROR err              = CHIP_NO_ERROR;
        const uint8_t __context_tag = std::get<uint8_t>(__element);

        if (__context_tag == to_underlying(Fields::kTimeToAdd))
        {
            err = DataModel::Decode(reader, timeToAdd);
        }
        else
        {
        }

        ReturnErrorOnFailure(err);
    }
}
} // namespace AddMoreTime.
} // namespace Commands
} // namespace MicrowaveOvenControl
} // namespace Clusters
} // namespace app
} // namespace chip
