## IDF Component Manager Manifest File
dependencies:
    espressif/mdns:
        version: "^1.1.0"
        rules:
            - if: "idf_version >=5.0"
            - if: "target != esp32h2"

    espressif/esp_secure_cert_mgr:
        version: "^2.3.0"
        rules:
            - if: "idf_version >=4.3"

    espressif/esp_encrypted_img:
        version: "2.1.0"
        require: public
        rules:
            - if: "idf_version >=4.4"

    # TODO:
    #   - Insights compilation fails seemingly after
    #     https://github.com/espressif/esp-insights/pull/47
    #   - Switching version to 1.0.2 does not seem to work (it says version not found)
    #     wile 1.0.1 pulls in a esp_insights_cbor_encoder.c that uses SHA_SIZE which is
    #     undefined (unclear why c and header differ)
    # espressif/esp_insights:
    #     version: "1.0.1"
    #     require: public
    #     # There is an issue with IDF-Component-Manager when ESP Insights is included.
    #     # Issue: https://github.com/project-chip/connectedhomeip/issues/29125
    #     rules:
    #         - if: "idf_version >=5.0"
    #         - if: "target != esp32h2"

    espressif/esp_rcp_update:
        version: "1.2.0"
        rules:
            - if: "idf_version >=5.0"

    espressif/esp_delta_ota:
        version: "^1.1.0"
        require: public
        rules:
            - if: "idf_version >=4.3"
