steps:
    - name: gcr.io/cloud-builders/git
      args:
          - submodule
          - update
          - "--init"
          - "--recursive"
      id: Submodules
    - name: "connectedhomeip/chip-build-vscode:0.6.02"
      env:
          - PW_ENVIRONMENT_ROOT=/pwenv
      args:
          - "-c"
          - source ./scripts/bootstrap.sh
      id: Bootstrap
      waitFor:
          - Submodules
      entrypoint: /usr/bin/bash
      volumes:
          - name: pwenv
            path: /pwenv
      timeout: 900s

    - name: "connectedhomeip/chip-build-vscode:0.6.02"
      env:
          - PW_ENVIRONMENT_ROOT=/pwenv
      args:
          - >-
              ./scripts/build/build_examples.py --enable-flashbundle
              --target ameba-amebad-light
              --target ameba-amebad-pigweed
              --target android-arm-chip-tool
              --target android-arm64-chip-tool
              --target android-arm64-tv-casting-app
              --target android-arm64-tv-server
              --target android-x64-chip-tool
              --target bl602-light
              --target bouffalolab-BL706-IoT-DVK-light-rpc
              --target cc13x2x7_26x2x7-lock-ftd
              --target cc13x2x7_26x2x7-lock-mtd
              --target cc13x2x7_26x2x7-shell
              --target cyw30739-cyw930739m2evb_01-ota-requestor-no-progress-logging
              --target efr32-brd4161a-light-rpc
              --target efr32-brd4161a-lock
              --target efr32-brd4161a-switch
              --target efr32-brd4161a-window-covering
              --target efr32-brd4187c-window-covering
              --target esp32-c3devkit-all-clusters
              --target esp32-c3devkit-all-clusters-minimal
              --target esp32-devkitc-all-clusters-ipv6only
              --target esp32-devkitc-all-clusters-minimal-ipv6only
              --target esp32-devkitc-bridge
              --target esp32-devkitc-light-rpc
              --target esp32-devkitc-lock
              --target esp32-devkitc-ota-requestor-rpc
              --target esp32-devkitc-shell
              --target esp32-m5stack-all-clusters
              --target esp32-m5stack-all-clusters-ipv6only
              --target esp32-m5stack-all-clusters-minimal
              --target esp32-m5stack-all-clusters-minimal-ipv6only
              --target esp32-m5stack-all-clusters-minimal-rpc
              --target esp32-m5stack-all-clusters-minimal-rpc-ipv6only
              --target esp32-m5stack-ota-requestor
              --target genio-lighting-app
              --target imx-all-clusters-app
              --target imx-chip-tool
              --target imx-thermostat
              --target infineon-psoc6-all-clusters
              --target infineon-psoc6-all-clusters-minimal
              --target infineon-psoc6-light
              --target infineon-psoc6-lock
              --target k32w-contact-release
              --target k32w-light-release-no-ota
              --target k32w-lock-release
              --target k32w-shell-release
              --target linux-arm64-clang-all-clusters
              --target linux-arm64-clang-all-clusters-app-nodeps
              --target linux-arm64-clang-all-clusters-app-nodeps-ipv6only
              --target linux-arm64-clang-all-clusters-ipv6only
              --target linux-arm64-clang-all-clusters-minimal
              --target linux-arm64-clang-all-clusters-minimal-ipv6only
              --target linux-arm64-clang-bridge-ipv6only
              --target linux-arm64-clang-chip-tool
              --target linux-arm64-clang-chip-tool-ipv6only
              --target linux-arm64-clang-chip-tool-nodeps
              --target linux-arm64-clang-chip-tool-nodeps-ipv6only
              --target linux-arm64-clang-dynamic-bridge-ipv6only
              --target linux-arm64-clang-light
              --target linux-arm64-clang-light-ipv6only
              --target linux-arm64-clang-light-rpc
              --target linux-arm64-clang-light-rpc-ipv6only
              --target linux-arm64-clang-lock
              --target linux-arm64-clang-lock-ipv6only
              --target linux-arm64-clang-minmdns
              --target linux-arm64-clang-ota-provider-nodeps-ipv6only
              --target linux-arm64-clang-ota-requestor-nodeps-ipv6only
              --target linux-arm64-clang-shell-ipv6only
              --target linux-arm64-clang-thermostat-ipv6only
              --target linux-arm64-clang-tv-app-ipv6only
              --target linux-arm64-clang-tv-casting-app-ipv6only
              --target linux-x64-address-resolve-tool
              --target linux-x64-all-clusters
              --target linux-x64-all-clusters-nodeps
              --target linux-x64-all-clusters-nodeps-ipv6only
              --target linux-x64-all-clusters-coverage
              --target linux-x64-all-clusters-ipv6only
              --target linux-x64-all-clusters-minimal
              --target linux-x64-all-clusters-minimal-ipv6only
              --target linux-x64-bridge-ipv6only
              --target linux-x64-chip-cert
              --target linux-x64-chip-tool
              --target linux-x64-chip-tool-coverage
              --target linux-x64-chip-tool-nodeps-ipv6only
              --target linux-x64-dynamic-bridge-ipv6only
              --target linux-x64-light-rpc-ipv6only
              --target linux-x64-lock-ipv6only
              --target linux-x64-minmdns
              --target linux-x64-nl-test-runner
              --target linux-x64-ota-provider
              --target linux-x64-ota-provider-nodeps-ipv6only
              --target linux-x64-ota-requestor-nodeps-ipv6only
              --target linux-x64-rpc-console
              --target linux-x64-shell-ipv6only
              --target linux-x64-thermostat-ipv6only
              --target linux-x64-tv-app-ipv6only
              --target linux-x64-tv-casting-app-ipv6only
              --target mbed-CY8CPROTO_062_4343W-light-release
              --target mbed-CY8CPROTO_062_4343W-lock-release
              --target mbed-CY8CPROTO_062_4343W-pigweed-release
              --target mw320-all-clusters-app
              --target nrf-nrf52840dk-all-clusters
              --target nrf-nrf52840dk-all-clusters-minimal
              --target nrf-nrf52840dk-light-rpc
              --target nrf-nrf52840dk-lock
              --target nrf-nrf52840dk-pump
              --target nrf-nrf52840dk-pump-controller
              --target nrf-nrf52840dk-shell
              --target nrf-nrf52840dongle-light
              --target nrf-nrf5340dk-all-clusters
              --target nrf-nrf5340dk-all-clusters-minimal
              --target nrf-nrf5340dk-shell
              --target qpg-light
              --target qpg-shell
              --target telink-tlsr9518adk80d-light
              --target tizen-arm-light
              build
              --create-archives /workspace/artifacts/
      id: CompileAll
      waitFor:
          - Bootstrap
      entrypoint: ./scripts/run_in_build_env.sh
      volumes:
          - name: pwenv
            path: /pwenv

logsBucket: matter-build-automation-build-logs

# Global timeout for all steps
timeout: 21600s
queueTtl: 21600s

artifacts:
    objects:
        location: "gs://matter-build-automation-artifacts/$PROJECT_ID/$COMMIT_SHA/"
        paths: ["/workspace/artifacts/*.tar.gz"]

# Using higher CPU machines generally speeds up builds, except bootstrap is always
# slow.
options:
    machineType: "E2_HIGHCPU_32"
    diskSizeGb: 500
