name: Kotlin

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/kotlin-style.yaml"
      - "kotlin-detect-config.yaml"

jobs:
  detekt:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: natiginfo/action-detekt-all@1.23.0
        # Detekt seems not to like circular symlinks, so we set up
        # explicit paths below
        with:
          args: --parallel --build-upon-default-config --config kotlin-detect-config.yaml --input examples/android/CHIPTest,examples/android/CHIPTool,examples/java-matter-controller/java,src/controller/java

  ktlint:
    name: "Format check"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: "ktfmt"
        uses: rsookram/ktfmt-action@v1
        with:
          style: kotlinlang
