name: Kotlin - Detekt

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/kotlin-detekt.yaml"

jobs:
  detekt:
    runs-on: ubuntu-latest

    steps:
      - name: "checkout"
        uses: actions/checkout@v2

      - name: "detekt"
        uses: alaegin/Detekt-Action@v1.23.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewdog_reporter: github-pr-review
          detekt_build_upon_default_config: true
          detekt_config: kotlin-detect-config.yaml
          detekt_parallel: true
          # Detekt seems not to like circular symlinks, so exclude them
          detect_excludes: "**/third_party/**,**/connectedhomeip**"
