name: Kotlin - Detekt

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/kotlin-detekt.yaml"

 jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "detekt"
         uses: natiginfo/action-detekt-all@1.23.0
