name: ktfmt

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktfmt.yaml"

 jobs:
   ktlint:
     runs-on: ubuntu-latest

     steps:
       - uses: actions/checkout@v2

       - uses: actions/setup-java@v2
         with:
           distribution: 'adopt'
           java-version: '11'

       - name: "ktfmt"
         uses: rsookram/ktfmt-action@v1
         with:
           style: kotlinlang
